POST http://localhost:3001/pets/create
Content-Type: application/json

{
  "type": "dog",
  "name": "Professor Pawsenstein",
  "status": "available",
  "picture": "https://images.pexels.com/photos/444444/pexels-photo-444444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  "height": 15,
  "weight": 12.6,
  "color": "gray",
  "bio": "A wise and knowledgeable dog, always ready to teach you new tricks!",
  "hypoallergenic": true,
  "dietaryRestrictions": ["chicken", "blueberries"],
  "breed": "Canine Professor"
}

















